// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.4
// source: service/api.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ApiClient is the client API for Api service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApiClient interface {
	TriggerCounter(ctx context.Context, in *ApiRequest, opts ...grpc.CallOption) (*CounterReply, error)
	GetCounter(ctx context.Context, in *ApiRequest, opts ...grpc.CallOption) (*CounterReply, error)
	ResetCounter(ctx context.Context, in *ApiRequest, opts ...grpc.CallOption) (*ApiReply, error)
}

type apiClient struct {
	cc grpc.ClientConnInterface
}

func NewApiClient(cc grpc.ClientConnInterface) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) TriggerCounter(ctx context.Context, in *ApiRequest, opts ...grpc.CallOption) (*CounterReply, error) {
	out := new(CounterReply)
	err := c.cc.Invoke(ctx, "/Api/TriggerCounter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetCounter(ctx context.Context, in *ApiRequest, opts ...grpc.CallOption) (*CounterReply, error) {
	out := new(CounterReply)
	err := c.cc.Invoke(ctx, "/Api/GetCounter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) ResetCounter(ctx context.Context, in *ApiRequest, opts ...grpc.CallOption) (*ApiReply, error) {
	out := new(ApiReply)
	err := c.cc.Invoke(ctx, "/Api/ResetCounter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiServer is the server API for Api service.
// All implementations must embed UnimplementedApiServer
// for forward compatibility
type ApiServer interface {
	TriggerCounter(context.Context, *ApiRequest) (*CounterReply, error)
	GetCounter(context.Context, *ApiRequest) (*CounterReply, error)
	ResetCounter(context.Context, *ApiRequest) (*ApiReply, error)
	mustEmbedUnimplementedApiServer()
}

// UnimplementedApiServer must be embedded to have forward compatible implementations.
type UnimplementedApiServer struct {
}

func (UnimplementedApiServer) TriggerCounter(context.Context, *ApiRequest) (*CounterReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TriggerCounter not implemented")
}
func (UnimplementedApiServer) GetCounter(context.Context, *ApiRequest) (*CounterReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCounter not implemented")
}
func (UnimplementedApiServer) ResetCounter(context.Context, *ApiRequest) (*ApiReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetCounter not implemented")
}
func (UnimplementedApiServer) mustEmbedUnimplementedApiServer() {}

// UnsafeApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApiServer will
// result in compilation errors.
type UnsafeApiServer interface {
	mustEmbedUnimplementedApiServer()
}

func RegisterApiServer(s grpc.ServiceRegistrar, srv ApiServer) {
	s.RegisterService(&Api_ServiceDesc, srv)
}

func _Api_TriggerCounter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).TriggerCounter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Api/TriggerCounter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).TriggerCounter(ctx, req.(*ApiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetCounter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetCounter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Api/GetCounter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetCounter(ctx, req.(*ApiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_ResetCounter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).ResetCounter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Api/ResetCounter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).ResetCounter(ctx, req.(*ApiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Api_ServiceDesc is the grpc.ServiceDesc for Api service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Api_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TriggerCounter",
			Handler:    _Api_TriggerCounter_Handler,
		},
		{
			MethodName: "GetCounter",
			Handler:    _Api_GetCounter_Handler,
		},
		{
			MethodName: "ResetCounter",
			Handler:    _Api_ResetCounter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service/api.proto",
}
